### ISSUE TITLE
Get give_me_text API working offline

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/EmailParser#8]
Get the give_me_text API working offline and document it

**Comment by Shidash** [comment]
This is close to being done, we just need to update of DirCrawl is called here https://github.com/TransparencyToolkit/CrawlerManager/blob/master/app/crawlers/load_files.rb and add those instructions you wrote to the repo

**Comment by bnvk** [comment]
- [x] Document in [Harvester](https://github.com/TransparencyToolkit/Harvester#install-tika--tesseract-optional) and [KeepGrabbing](https://github.com/TransparencyToolkit/KeepGrabbing#emails)
- [ ] Implement in CrawlerManger

**Comment by bnvk** [comment]
Updated CrawlerManager in d132f7ad787d05a44d3a3e4d5502ef073aadb31a any further tracking of this implementation should be done in [Projects/issues](/TransparencyToolkit/Projects/issues)
